# Generated by Django 3.1.3 on 2021-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_mother',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(1, 'Doctor'), (2, 'Mother')], default=2),
        ),
    ]
