# Generated by Django 3.1.3 on 2021-02-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210219_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_color',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
