# Generated by Django 3.1.3 on 2021-02-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
