# Generated by Django 3.1.3 on 2021-02-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210220_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_color',
            field=models.CharField(default='25a207', max_length=20),
        ),
    ]
