# Generated by Django 3.1.3 on 2021-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210220_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_color',
            field=models.CharField(default='753ddb', max_length=20),
        ),
    ]
